# Generated by Django 4.0.3 on 2022-04-05 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('IDperfil', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrobaUsuario', models.CharField(max_length=30)),
                ('URLPerfil', models.CharField(max_length=255)),
                ('numSeguidores', models.FloatField()),
                ('numPostagens', models.IntegerField()),
                ('numSeguidas', models.IntegerField()),
                ('createRegister', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
