# Generated by Django 4.0.3 on 2022-04-05 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('nomeCurso', models.CharField(max_length=30)),
                ('IDcurso', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nomeAluno', models.CharField(max_length=35)),
                ('idadeAluno', models.IntegerField()),
                ('IDaluno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Turma', models.IntegerField()),
                ('departamento', models.CharField(max_length=30)),
                ('createRegister', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
